DROP TABLE category CASCADE;

CREATE TABLE category(
    id              serial          PRIMARY KEY,
    name            varchar         NOT NULL,
    section_id      int             NOT NULL        REFERENCES section(id) ON DELETE CASCADE
);

INSERT INTO category VALUES
(nextval('category_id_seq'), 'Smartphones', 1),
(nextval('category_id_seq'), 'Smartwatches', 1),
(nextval('category_id_seq'), 'Tablets', 1),
(nextval('category_id_seq'), 'Laptops', 1),
(nextval('category_id_seq'), 'PCs', 1),
(nextval('category_id_seq'), 'Printers', 1),
(nextval('category_id_seq'), 'Computer parts', 1),
(nextval('category_id_seq'), 'Accessories', 1),
(nextval('category_id_seq'), 'TVs', 1),
(nextval('category_id_seq'), 'Consoles', 1),
(nextval('category_id_seq'), 'Dishwashers', 1),
(nextval('category_id_seq'), 'Washing machines', 1),
(nextval('category_id_seq'), 'Cameras', 1),
(nextval('category_id_seq'), 'Microwaves', 1),
(nextval('category_id_seq'), 'Fridges', 1),

(nextval('category_id_seq'), 'Shoes', 2),
(nextval('category_id_seq'), 'Underwear', 2),
(nextval('category_id_seq'), 'Watches', 2),
(nextval('category_id_seq'), 'Jewellery', 2),
(nextval('category_id_seq'), 'Dresses', 2),
(nextval('category_id_seq'), 'T-Shirts', 2),
(nextval('category_id_seq'), 'Pants', 2),
(nextval('category_id_seq'), 'Suites', 2),
(nextval('category_id_seq'), 'Jackets', 2),
(nextval('category_id_seq'), 'Accessories', 2),

(nextval('category_id_seq'), 'Carpets', 3),
(nextval('category_id_seq'), 'Bedding', 3),
(nextval('category_id_seq'), 'Blankets', 3),
(nextval('category_id_seq'), 'Towels', 3),
(nextval('category_id_seq'), 'Pots', 3),
(nextval('category_id_seq'), 'Pans', 3),
(nextval('category_id_seq'), 'Accessories', 3),
(nextval('category_id_seq'), 'Cutlery', 3),
(nextval('category_id_seq'), 'Tools', 3),
(nextval('category_id_seq'), 'Lamps', 3),
(nextval('category_id_seq'), 'Furniture', 3),
(nextval('category_id_seq'), 'Heating', 3),
(nextval('category_id_seq'), 'Hydraulics', 3),
(nextval('category_id_seq'), 'Electricity', 3),
(nextval('category_id_seq'), 'Elevation', 3),
(nextval('category_id_seq'), 'Gardening tools', 3),

(nextval('category_id_seq'), 'Coffee', 4),
(nextval('category_id_seq'), 'Tea', 4),
(nextval('category_id_seq'), 'Healthy food', 4),
(nextval('category_id_seq'), 'Nuts', 4),
(nextval('category_id_seq'), 'Decorations', 4),
(nextval('category_id_seq'), 'Olives', 4),
(nextval('category_id_seq'), 'Oils', 4),
(nextval('category_id_seq'), 'Dog food', 4),
(nextval('category_id_seq'), 'Cat food', 4),
(nextval('category_id_seq'), 'Rodent food', 4),

(nextval('category_id_seq'), 'Shampoos', 5),
(nextval('category_id_seq'), 'Bath accessories', 5),
(nextval('category_id_seq'), 'Shower gels', 5),
(nextval('category_id_seq'), 'Hair dyes', 5),
(nextval('category_id_seq'), 'Manicure', 5),
(nextval('category_id_seq'), 'Pedicure', 5),
(nextval('category_id_seq'), 'Makeup', 5),

(nextval('category_id_seq'), 'Contact lenses', 6),
(nextval('category_id_seq'), 'Inhalers', 6),
(nextval('category_id_seq'), 'Thermometers', 6),
(nextval('category_id_seq'), 'Hearing aid', 6),
(nextval('category_id_seq'), 'Herbs', 6),
(nextval('category_id_seq'), 'Painkillers', 6),

(nextval('category_id_seq'), 'Fantasy books', 7),
(nextval('category_id_seq'), 'Crime stories books', 7),
(nextval('category_id_seq'), 'Children books', 7),
(nextval('category_id_seq'), 'Science books', 7),
(nextval('category_id_seq'), 'School books', 7),
(nextval('category_id_seq'), 'Music albums', 7),
(nextval('category_id_seq'), 'Video games', 7),
(nextval('category_id_seq'), 'Guitars', 7),
(nextval('category_id_seq'), 'Drums', 7),
(nextval('category_id_seq'), 'Pre-paid cards', 7),
(nextval('category_id_seq'), 'Movies', 7),

(nextval('category_id_seq'), 'Bikes', 8),
(nextval('category_id_seq'), 'Helmets', 8),
(nextval('category_id_seq'), 'Fishing rods', 8),
(nextval('category_id_seq'), 'Fishing accessories', 8),
(nextval('category_id_seq'), 'Sleeping bags', 8),
(nextval('category_id_seq'), 'Survival tools', 8),
(nextval('category_id_seq'), 'Sport rifles', 8),
(nextval('category_id_seq'), 'Scooters', 8),
(nextval('category_id_seq'), 'ASG', 8),
(nextval('category_id_seq'), 'Paintball', 8),
(nextval('category_id_seq'), 'Skating', 8),
(nextval('category_id_seq'), 'Water sports', 8),

(nextval('category_id_seq'), 'Cars', 9),
(nextval('category_id_seq'), 'Trucks', 9),
(nextval('category_id_seq'), 'Suspension', 9),
(nextval('category_id_seq'), 'Brakes', 9),
(nextval('category_id_seq'), 'Tires', 9),
(nextval('category_id_seq'), 'Rims', 9),
(nextval('category_id_seq'), 'Spoilers', 9),
(nextval('category_id_seq'), 'Motorcycles', 9),
(nextval('category_id_seq'), 'Cooling system', 9),
(nextval('category_id_seq'), 'Lamps', 9),
(nextval('category_id_seq'), 'Floor mats', 9),
(nextval('category_id_seq'), 'Car parts', 9);